#! /bin/bash
echo "Script Arguments List"
echo "\$* Value= $*"
echo "\$@ Value= $@"
echo "\$0 Value= $0"
echo "\$1 Value= $1"
echo "\$2 Value= $2"
echo "\$3 Value= $3"
echo "\$4 Value= $4"
echo "\$5 Value= $5"
echo "\$# Value= $#  Total Arguments count"
echo "\$$ Value= $$"
